Other style of loop.

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -253,16 +253,15 @@ clone_stop:
 📁yaml_validation:
   <<: *yaml_validate
   script:
-    - CHANGED_FILES=$(git diff --name-only $CI_COMMIT_BEFORE_SHA $CI_COMMIT_SHA)
-    - echo "Changed files: $CHANGED_FILES"
-    - for file in $CHANGED_FILES; do 
-        if python -c "import yaml; yaml.safe_load(open('$file'))" > /dev/null 2>&1; then
-        echo "YAML validation passed for $file"
-        else
-        echo "YAML validation failed for $file"
-        exit 1
-        fi
-        done
+    # Iterate over each changed YAML file using Python's yaml.safe_load
+    for file in $CHANGED_FILES; do
+    if python -c "import yaml; yaml.safe_load(open('$file'))" > /dev/null 2>&1; then
+    echo "YAML validation passed for $file"
+    else
+    echo "YAML validation failed for $file"
+    exit 1
+    fi
+    done
   allow_failure: false
 
 .permifrost: &permifrost
